### ISSUE TITLE
Kanban board submission

### ISSUE THREAD

**Issue by keebot-png** [keebot-png/booking-front-end#11]
## List of requirements:
- [x] There are four team members in total.
- [x] Kanban board [LINK](https://github.com/users/keebot-png/projects/3/views/1).
## Screenshot of the kanban board:
<img src='https://user-images.githubusercontent.com/101398701/228822583-e23a3acd-3c86-4a44-960e-d512e53cb2e6.png' />

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


## Highlights
- I like that you separated between front-end and back-end 👍 
- You have descriptions for each task 👍 

##  suggestions
- You are required that all members of have equitable distribution of points where the difference between any two emmeber should no be greater than 5.  Difference <= 5 points. There is a case where one team member has 17 and two other have 9. Try to distribute the tasks so that it maybe 4 a point difference?. There even may be tasks where you understimate the time it will take. Front-End usually takes longer than maybe what you're proposing.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by keebot-png** [comment]
@mcrd25 Apologies, I will fix the issue so that there won't be a deviance of more than 5 points.

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 




Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
